/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.moaxcp.gradleanimation;

import java.util.List;
import java.util.Set;
import javax.inject.Inject;
import org.gradle.api.*;
import org.gradle.api.execution.TaskExecutionGraph;
import org.gradle.api.execution.TaskExecutionGraphListener;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.TaskState;
import org.gradle.build.event.BuildEventsListenerRegistry;
import org.gradle.tooling.events.OperationCompletionListener;

/**
 * A simple 'hello world' plugin.
 */
public class GradleTaskAnimationPlugin implements Plugin<Project>, TaskExecutionGraphListener {

    public void apply(Project project) {
        project.getGradle().getTaskGraph().addTaskExecutionGraphListener(this);
    }

    @Override
    public void graphPopulated(TaskExecutionGraph taskGraph) {
        taskGraph.afterTask(task -> {

        });
        List<Task> tasks = taskGraph.getAllTasks();
        for(Task task : tasks) {
            String name = task.getName();
            Set<Task> dependencies = taskGraph.getDependencies(task);
        }
    }
}
